title: M Havid Albar P - Portfolio
author: Mochamad Havid Albar Purnomo
email: havidalbar@gmail.com
description: M Havid Albar P - Portfolio; Machine Learning, Deep Learning, Apps
url: "https://havidalbar.github.io/"
github_username: havidalbar
image: favicons\havidalbar.jpg

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
